project_id = "pqrslnydcrpjelpzdnyp"

[functions.process-email-queue]
verify_jwt = true

[functions.send-transactional-email]
verify_jwt = false

[functions.preview-transactional-email]
verify_jwt = false

[functions.handle-email-unsubscribe]
verify_jwt = false

[functions.handle-email-suppression]
verify_jwt = false

[functions.inbound-email-webhook]
verify_jwt = false

[functions.calcom-slots]
verify_jwt = false

[functions.expire-slot-holds]
verify_jwt = false

[functions.inbound-webhook]
verify_jwt = false

[functions.calcom-confirm-booking]
verify_jwt = false

[functions.reset-test-data]
verify_jwt = false
